### ISSUE TITLE
Modmanager blank

### ISSUE THREAD

**Issue by junglejuz** [Raicuparta/ow-mod-manager#133]
Just getting an empty white screen when launching OuterWildsModManager.exe. No interface is available to do anything with. Have trried the installer and the portable version. Same issue with both.

![image](https://user-images.githubusercontent.com/40817462/132222794-5f229177-4f98-46cb-b177-b9c44a71cc44.png)

**Comment by Raicuparta** [comment]
Find your logs file in `C:/Users/[YOUR_USER_NAME]/AppData/Roaming/OuterWildsModManager/logs/main.log`

Send me the file.

**Comment by junglejuz** [comment]
[main.log](https://github.com/Raicuparta/ow-mod-manager/files/7117017/main.log)

**Comment by Raicuparta** [comment]
Well, that turned out to be really useless didn't it. Another thing you could try if you feel like it: open a terminal window (WIN+R, typing `cmd`, then press enter). Then drag the `OuterWildsModManager.exe` file to the black cmd window, and press enter. It should run the manager again, but showing the logs in the cmd window. Perhaps the logs there say something more useful?

**Comment by junglejuz** [comment]
![image](https://user-images.githubusercontent.com/40817462/132342980-82da98dd-031e-4858-8549-713937dd3c83.png)

**Comment by Raicuparta** [comment]
Yeah, no help... Don't know what else to do, sorry.

You can get the mods without the manager by downloading OWML yourself, and then the mods. Download the latest OWML.zip here: https://github.com/amazingalek/owml/releases. And follow the manual installation steps here: https://github.com/amazingalek/owml#installation
