### ISSUE TITLE
(Bug) White screen of death after setting OWAlpha path

### ISSUE THREAD

**Issue by Owen013** [Raicuparta/ow-mod-manager#163]
![2022-05-27](https://user-images.githubusercontent.com/96493201/170724678-cc739cf8-f9fe-416b-a8a4-c0d31c741c71.png)

**Comment by Raicuparta** [comment]
I uploaded another prerelease: https://github.com/Raicuparta/ow-mod-manager/releases/download/v1.11.0-pre1/OuterWildsModManager-Portable.zip

I think the problem you're having is related to the path you set not being accessible by the manager. Usually this is because of missing permissions, or maybe due to being in another drive. This version shouldn't crash anymore in those cases (although it will still be a bit confusing since it will just erase the path). In other cases, it should now show you a proper error message instead of a white screen.
